apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arch
  template:
    metadata:
      labels:
        app: arch
    spec:
      containers:
      - name: arch
        image: picawoo/arch:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: arch-config
        volumeMounts:
        - name: logs-storage
          mountPath: /app/logs
      volumes:
      - name: logs-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: arch-service
spec:
  selector:
    app: arch
  ports:
  - port: 80
    targetPort: 5000